version: '3.9'

services:
  java_app:
    container_name: java_app
    image: monarcaproject-java-app
    build: ./BackEnd/BackEndMonarca
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/monarcaweb
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: monarcaweb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  vite-app:
    image: node:alpine
    container_name: vite-app
    entrypoint: /bin/sh
    ports:
      - "3000:3000"
    working_dir: /srv/app
    volumes:
      - type: bind
        source: FrontEnd
        target: /srv/app
    tty: true

volumes:
  db_data: